# Suppose we want to estimate the average weight of an adult male in    Mexico. We draw a random sample of 2,000 men from a population of 3,000,000 men and weigh them. We find that the average person in our sample weighs 200 pounds, and the standard deviation of the sample is 30 pounds. Calculate 94%,98%,96% confidence interval?

Here given Total Population=3000000,n=2000 , mean(sample)=200,std of sample=30, we have to find Confidence intervals of 94,96 and 98%. Since Standard Deviation of population is not given , we will be taking t test

In [5]:
import pandas as pd
import numpy as np
from scipy import stats

In [ ]:
#Confidence Interval for 94%

In [6]:
tint_94=stats.t.interval(0.94,loc=200,df=1999,scale=30/np.sqrt(2000))
tint_94

(198.7376089443071, 201.2623910556929)

In [4]:
np.round(tint_94)

array([199., 201.])

In [7]:
#Confidence Interval for 98%

In [9]:
tint_98=stats.t.interval(0.98,loc=200,df=1999,scale=30/np.sqrt(2000))
tint_98

(198.4381860483216, 201.5618139516784)

In [10]:
np.round(tint_98)

array([198., 202.])

In [11]:
#Confidence Interval of 96%

In [12]:
tint_96=stats.t.interval(0.96,loc=200,df=1999,scale=30/np.sqrt(2000))
np.round(tint_96)

array([199., 201.])