In [102]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

# Question 1.A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.
Minitab File : Cutlets.mtw


Here we will be using t-test for 2 numerical samples

Step 1 : Null Hypothesis                                                                                                  [cutlets1 𝜇1=cutlets1 𝜇2 ; Alternate Hypothesis cutlets1 𝜇1 ≠ cutlets2𝜇2]

Step2 :Read the cutlets data

In [25]:
data1=pd.read_csv('Cutlets.csv')
data1

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

Step3 : Segregate the data and visualise it

In [26]:
data11=data1[['Unit A']]
data11

Unit A
0   6.8090
1   6.4376
2   6.9157
3   7.3012
4   7.4488
5   7.3871
6   6.8755
7   7.0621
8   6.6840
9   6.8236
10  7.3930
11  7.5169
12  6.9246
13  6.9256
14  6.5797
15  6.8394
16  6.5970
17  7.2705
18  7.2828
19  7.3495
20  6.9438
21  7.1560
22  6.5341
23  7.2854
24  6.9952
25  6.8568
26  7.2163
27  6.6801
28  6.9431
29  7.0852
30  6.7794
31  7.2783
32  7.1561
33  7.3943
34  6.9405

In [27]:
data12=data1[['Unit B']]
data12

Unit B
0   6.7703
1   7.5093
2   6.7300
3   6.7878
4   7.1522
5   6.8110
6   7.2212
7   6.6606
8   7.2402
9   7.0503
10  6.8810
11  7.4059
12  6.7652
13  6.0380
14  7.1581
15  7.0240
16  6.6672
17  7.4314
18  7.3070
19  6.7478
20  6.8889
21  7.4220
22  6.5217
23  7.1688
24  6.7594
25  6.9399
26  7.0133
27  6.9182
28  6.3346
29  7.5459
30  7.0992
31  7.1180
32  6.6965
33  6.5780
34  7.3875

In [105]:
fig, axes = plt.subplots(1, 2, figsize=(10, 5))

# Plot histograms in each subplot
data11.plot.hist(ax=axes[0], bins=10, alpha=0.7, color='blue')
axes[0].set_title('Cutlets 1')
axes[0].set_xlabel('Values')
axes[0].set_ylabel('Frequency')

data12.plot.hist(ax=axes[1], bins=10, alpha=0.7, color='green')
axes[1].set_title('Cutlets 2')
axes[1].set_xlabel('Values')
axes[1].set_ylabel('Frequency')

# Show the plot
plt.tight_layout()
plt.show()


In [28]:
cutlets1=pd.DataFrame(data11)
cutlets2=pd.DataFrame(data12)

Step3:Performing t-test for above data

In [29]:
t_statistic,p_value=stats.ttest_ind(cutlets1,cutlets2, alternative='two-sided')
t_statistic,p_value

(array([0.72286887]), array([0.47223947]))

Step4:Result and Interpretation

Here significance level , alpha=0.05

In [107]:
alpha=0.05

In [108]:
if p_value > alpha:
    print("Result='We accept Null Hypothesis'")
    print('Interpretation- Cutlets of Unit A and Unit B are of same sizes ')
else:
    print("Result='We dont accept Null Hypothesis'")
    print('Interpretation- Cutlets of Unit A and Unit B are of different sizes ')
    

Result='We accept Null Hypothesis'
Interpretation- Cutlets of Unit A and Unit B are of same sizes 


# ---------------------------------------------------------------------------------------------------------------

# Question 2.A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.
 
 
    
    Minitab File: LabTAT.mtw


Here we will be using ANOVA test f-statistics for more than 2 samples

Step 1:Null Hypothesis [Means of Laboratory 1,Laboratory 2,Laboratory 3,Laboratory 4 ] are same
       Alternate Hypothesis , atleast one mean of above laboratories are different

Step2:Read the data

In [32]:
data2=pd.read_csv("LabTAT.csv")
data2

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [33]:
data21=data2[['Laboratory 1']]
data22=data2[['Laboratory 2']]
data23=data2[['Laboratory 3']]
data24=data2[['Laboratory 4']]

In [34]:
Lab1=pd.DataFrame(data21)
Lab2=pd.DataFrame(data22)
Lab3=pd.DataFrame(data23)
Lab4=pd.DataFrame(data24)

In [35]:
Lab1_mean=Lab1.mean()
Lab1_mean

Laboratory 1    178.361583
dtype: float64

In [36]:
Lab2_mean=Lab2.mean()
Lab2_mean

Laboratory 2    178.902917
dtype: float64

In [37]:
Lab3_mean=Lab3.mean()
Lab3_mean

Laboratory 3    199.91325
dtype: float64

In [38]:
Lab4_mean=Lab4.mean()
Lab4_mean

Laboratory 4    163.68275
dtype: float64

Step3:Perform ANOVA f-statistics

In [39]:
stats.f_oneway(Lab1,Lab2,Lab3,Lab4)

F_onewayResult(statistic=array([118.70421654]), pvalue=array([2.11567089e-57]))

Step4: Result and Interpretation

Here significance level , alpha=0.05

In [40]:
alpha=0.05

In [97]:
if p_value > alpha:
    print("Result='We accept Null Hypothesis'")
    print('Interpretation- "There is no significant difference in average TAT among different laboratories." ')
else:
    print("Result='We dont accept Null Hypothesis'")
    print('Interpretation- "There is a significant difference in average TAT among different laboratories."')


Result='We accept Null Hypothesis'
Interpretation- "There is no significant difference in average TAT among different laboratories." 


# ---------------------------------------------------------------------------------------------------------------

# Question 3.Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.
        

Here we will be using ChiSquare , Test of Independence

Step1:

Null Hypothesis -There is no significant relationship between gender and region.The Male Female Buyerratios are same

Alternate Hypothesis -There is a significant relationship between gender and region.The Male Female Buyerratios are not same.

Step2: Read the data

In [20]:
data3=pd.read_csv('BuyerRatio.csv')
data3

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [42]:
Male=[50,142,131,70]
Female=[435,1523,1356,750]
buyerratio=[Male,Female]
buyerratio

[[50, 142, 131, 70], [435, 1523, 1356, 750]]

Step3: Doing Chi2_Contingency test of Independence

In [51]:
stat,p,dof,expected=stats.chi2_contingency(buyerratio)
print ('p=',p)
print('dof=',dof)

p= 0.6603094907091882
dof= 3


In [52]:
expected

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

Step4: Result and Interpretation

Here we assume significance level alpha=0.05

In [55]:
alpha=0.05

In [57]:
if p_value > alpha:
    print("Result='We accept Null Hypothesis'")
    print('Interpretation- "There is no significant relationship between gender and region.The Male Female Buyerratios are same." ')
else:
    print("Result='We dont accept Null Hypothesis'")
    print('Interpretation- "There is a significant relationship between gender and region.The Male Female Buyerratios are not same."')


Result='We accept Null Hypothesis'
Interpretation- "There is no significant relationship between gender and region.The Male Female Buyerratios are same." 


# ---------------------------------------------------------------------------------------------------------------

# Question 4.TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences

Minitab File: CustomerOrderForm.mtw

Here we will be using ChiSquare , Test of Independence

Step1:

Null Hypothesis -The Male Female Buyerratios are sameThere is no significant relationship between centre and defectivness.

Alternate Hypothesis -There is a significant relationship between centre and defectiveness.

Step2: Read the data

In [77]:
data4=pd.read_csv('Costomer+OrderForm.csv')
data4

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

Step3: Value the counts in each country and making it in a table

In [83]:
Phillippines_count=data4['Phillippines'].value_counts()
Phillippines_count

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [84]:
Indonesia_count=data4['Indonesia'].value_counts()
Indonesia_count

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [85]:
Malta_count=data4['Malta'].value_counts()
Malta_count

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [86]:
India_count=data4['India'].value_counts()
India_count

Error Free    280
Defective      20
Name: India, dtype: int64

In [93]:
data41={'Country':['Phillippines','Indonesia','Malta','India'],
'Error_free':[271,267,269,280],
'Defective':[29,33,31,20]}
#Customer Data Form-cof
cof=pd.DataFrame(data41)
table=cof.set_index('Country')[['Error_free','Defective']]
table

Error_free  Defective
Country                            
Phillippines         271         29
Indonesia            267         33
Malta                269         31
India                280         20

Step4:Performing Chi2_COntingency test

In [95]:
stat,p,dof,expected=stats.chi2_contingency(table)
print('p=',p)
print('dof=',dof)

p= 0.2771020991233144
dof= 3


In [99]:
expected

array([[271.75,  28.25],
       [271.75,  28.25],
       [271.75,  28.25],
       [271.75,  28.25]])

Step 5: Result and Interpretation

Here Significance level , alpha=0.05

In [98]:
alpha=0.05

In [100]:
if p_value > alpha:
    print("Result='We accept Null Hypothesis'")
    print('Interpretation- "There is no significant relationship between centre and defective." ')
else:
    print("Result='We dont accept Null Hypothesis'")
    print('Interpretation- "There is a significant relationship between centre and defectiveness."')

Result='We accept Null Hypothesis'
Interpretation- "There is no significant relationship between centre and defective." 


# ---------------------------------------------------------------------------------------------------------------